app1/urls.py
from django.urls import path

from . import views

app_name= "app1"
urlpatterns = [
    path('minv', views.mng_inv, name='manage_inv'),
    path('tinv', views.trck_inv, name='track_inv'),
    path('orders', views.s_orders, name='sales_orders'),
    path('orders/<str:oaction>/<int:oid>', views.mng_order, name='mng_order'),
    path('prod/<int:prodid>', views.prod, name='product'),
]

app2/urls.py
from django.urls import path

from . import views

app_name= "app2"
urlpatterns = [
    path('users', views.users, name='users'),
    path('users/manage/<str:uaction>/<int:uid>', views.mng_user, name='manage_user'),
    path('users/profile/<int:uid>', views.view_prof, name='view_profile'),
]

#path('profile'
'''
    path('minv', views.mng_inv, name='manage_inv'),
    path('tinv', views.trck_inv, name='track_inv'),
    path('orders', views.s_orders, name='sales_orders'),
    path('orders/<str:oaction>/<int:oid>', views.mng_order, name='mng_order'),
    path('prod/<int:prodid>', views.prod, name='product'),
'''

app2/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, Permission, AbstractUser
)



class User1(AbstractUser):
    uaddr= models.CharField(blank=True, max_length=100)
    udob = models.DateField(null=True, blank=True)
    uemp= models.CharField(blank=True, max_length=100)
    
    class Meta:
        permissions = [
            ("mng_users", "manage users is_active etc"),
        ]

#----------------------------------------------------#

'''
class MyUserManager(BaseUserManager):
    def create_user(self, uname,uemail, password=None):
        if not uname or not uemail:
            raise ValueError('Please provide all mandatory fields')

        user = self.model(uname=uname,uemail=uemail)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, uname,uemail ,password=None):

        user = self.create_user(
            uname=uname, uemail=uemail
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    uname= models.CharField(max_length=10,unique=True)
    uemail = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    ufname= models.CharField(max_length=20)
    ulname= models.CharField(max_length=20)
    uaddr= models.CharField(max_length=100)
    udob = models.DateField(null=True, blank=True)
    uemp= models.CharField(max_length=100) #user-employer

    user_permissions= models.ManyToManyField(Permission) 
    
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    
    
    objects = MyUserManager()

    USERNAME_FIELD = 'uname'
    REQUIRED_FIELDS = ['uemail']
    #USERNAME_FIELD & pwd : no need to mention / always prompted/reqd

    def __str__(self):
        return self.uname
    
    
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
    
'''

app2/views.py
from django.shortcuts import render

from django.urls import reverse
from datetime import datetime
from django.contrib.auth.decorators import login_required,permission_required
from django.core.exceptions import PermissionDenied
import logging
logger = logging.getLogger(__name__) # Get an instance of a logger
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect,Http404

from app2.admin import UserChangeForm as UserForm
from app2.models import User1
# Create your views here.


@login_required()
@permission_required('app2.mng_users', raise_exception=True)
def users(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        '''
        # create a form instance and populate it with data from the request:
        form = SOrderItemForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            
            fd= form.cleaned_data
            so= SOrder_item.objects.all().order_by("-ssno")
            if len(so)==0:
                fd["ssno"]= 1
            else:
                fd["ssno"]= so[0].ssno + 1
            fp= int(fd["sprod"].pmrp * ((100-fd["sdisc"])/100))
            fd["sfp"]= fp
            soi= SOrder_item(**fd)
            soi.save()
        '''
        # redirect to a new URL:
        return HttpResponseRedirect(reverse('app2:users'))
            
    # if a GET (or any other method) we'll create a blank form
    else:
        uitems= User1.objects.all().order_by("username")
        snos= range(1,len(uitems)+1)

        context= {"items":zip(snos,uitems)}
        return render(request, 'app2/upd_users.html', context )
        ##orig indent= inline with if-else ##test


@login_required()
def mng_user(request,uaction,uid):
    logger.error(uaction+str(uid)+str(request.user.id))
    if request.method == 'POST':
        logger.error(uaction+str(uid)+str(request.user.id))
        req_user= User1.objects.get(id=request.user.id)
        prof_user= User1.objects.get(id=uid)
        if req_user.has_perm("app2.mng_users"):
            if(uaction=="Activate"):
                prof_user.is_active= True; prof_user.save()
            elif(uaction=="Deactivate"):
                prof_user.is_active= False; prof_user.save()
            elif(uaction=="Change_Pwd"):
                prof_user.set_password(request.POST["new_pwd"])
                prof_user.save()
        elif request.user.id==uid:
            if(uaction=="Change_Pwd"):
                if prof_user.check_password(request.POST["old_pwd"]):
                    prof_user.set_password(request.POST["new_pwd"])
                    prof_user.save()
                else:
                    return HttpResponse("Wrong current-password entered..!")
        else:
            raise PermissionDenied()

        nexturl=request.POST.get("next_url")
        if nexturl:
            nurl= nexturl.split("|")[0]; nargs= nexturl.split("|")[1:]
            return HttpResponseRedirect(reverse(nurl,args=nargs))
        else:
            return HttpResponseRedirect(reverse('app2:users'))

@login_required()
def view_prof(request,uid):
    if request.method == 'GET':
        req_user= User1.objects.get(id=request.user.id)
        prof_user= User1.objects.get(id=uid)
        '''user= User1.objects.get(id=uid)
        if request.user.has_perm("app2.view_profile",obj=user):'''
        if uid==request.user.id or req_user.has_perm("app2.mng_users"):
            context={"user":prof_user}
            return render(request, 'app2/view_profile.html', context )
        else:
            raise PermissionDenied()
            
    
    

app2/templates/app2/upd_users.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Update Users</title>
	<style>
	th, td {
	text-align: center;
	padding: 10px 0px 10px 0px;  {#t r b l}
	}
	
	th {
	border-bottom: 1px solid black;
	}

	td {
	border-bottom: 1px solid #ddd;
	}

	table {
	border: 1px solid black;
	border-collapse: collapse;
	}

	.align2center {
  	margin-left: auto;
  	margin-right: auto;
	}

	.align2bottomleft {
  	margin-left: 0px;
  	margin-bottom: 0px;
	}
	</style>
  </head>
  <body>
{% load custom_template_tags %}
	{% if items %}
		<table style="width:80%" class="align2center">
		<tr>
		<th>S.No</th>
		<th>UserName</th>
		<th>Email</th>
		<th>Active status</th>
		<th>Manage User</th>
		</tr>
		{% for sno,item in items %}
			<tr>
			<td>{{sno}}</td><td>{{item.username}}</td>
			<td>{{item.email}}</td><td>{{item.is_active}}</td>
			{% if item.is_active %}
				{% setvar "Deactivate" as action %}
			{% else %}
				{% setvar "Activate" as action %}
			{% endif %}
			<td><p><form>
				{% csrf_token %}
				<button 
				formaction="{% url 'app2:manage_user' action item.id %}"
				formmethod="post"
				type="submit">{{ action }}</button>
			    </form></p>
			    <a href="{% url 'app2:view_profile' item.id %}" target="_blank">
				<button type="button">Open Profile</button></a>
			    
			</td>	
			</tr>
		{% endfor %}
		</ul>
	{% else %}
		<p>No users are available.</p>
		</table>
	{% endif %}
	
	<table style="position: fixed; right: 30px; bottom: 50px; border:0;"><tr>
		<td style="border=0; padding:5px"><a href="{% url "homeview" %}"><button>Home</button></a></td>
    		<td style="border=0; padding:5px"><a href="{% url "logout" %}"><button>Logout</button></a></td>
	</tr></table>

{% comment %}
	<label for="update">Update Order #No:</label>
		<input type="text" name="upd_sno">
		<input type="submit" value="Update order" formaction="{% url 'app1:mng_order' "upd" "0" %}">
	
	 <li><a href="{% url 'app1:product' prd.psno %}">{{prd.pname}}</a></td><td>;;{{prd.pmf}}</a></li> 
{% endcomment %}
  </body>
</html>

app2/templates/app2/view_profile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>View Profile</title>
	<style>
	th, td {
	text-align: center;
	padding: 10px 0px 10px 0px;  {#t r b l}
	}
	
	th {
	border-right: 1px solid #ddd;
	}

	td {
	border-bottom: 0px solid #ddd;
	}

	table {
	border: 2px solid black;
	border-collapse: collapse;
	}

	.align2center {
  	margin-left: auto;
  	margin-right: auto;
	}

	.align2bottomleft {
  	margin-left: 0px;
  	margin-bottom: 0px;
	}
	</style>
  </head>
  <body>
{% load custom_template_tags %}
{# {% if items %} #}




		<table style="width:80%">
		<tr><th>UserName</th> <td>{{user.username}}</td></tr>
		<tr><th>Email</th> <td>{{user.email}}</td></tr>
		<tr><th>First Name</th> <td>{{user.first_name}}</td></tr>
		<tr><th>Last Name</th> <td>{{user.last_name}}</td></tr>
		<tr><th>Date of birth</th> <td>{{user.udob}}</td></tr>
		<tr><th>Employer Name</th> <td>{{user.uemp}}</td></tr>
		<tr><th>Address</th> <td>{{user.uaddr}}</td></tr>
		</table>

<p>		
<form action="{% url "app2:manage_user" "Change_Pwd" user.id%}" method="post">
    	{% csrf_token %}
	<input type="hidden" name="next_url" value="app2:view_profile|{{user.id}}">

	<label for="old_pwd">Current password: (Optional: if you're a store-owner)</label>
	<input type="password" name="old_pwd">
	<label for="old_pwd">New password:</label>
	<input type="password" name="new_pwd">
	<input type="submit" value="Change Password">
</form>
</p>		

	<table style="position: fixed; right: 30px; bottom: 50px; border:0;"><tr>
		<td style="border=0; padding:5px"><a href="{% url "homeview" %}"><button>Home</button></a></td>
    		<td style="border=0; padding:5px"><a href="{% url "logout" %}"><button>Logout</button></a></td>
	</tr></table>






{% comment %}		
		{% for sno,item in items %}
			<tr>
			<td>{{sno}}</td><td>{{item.username}}</td>
			<td>{{item.email}}</td><td>{{item.is_active}}</td>
			{% if item.is_active %}
				{% setvar "Deactivate" as action %}
			{% else %}
				{% setvar "Activate" as action %}
			{% endif %}
			<td><form method="post">
				{% csrf_token %}
				<button 
				formaction="{% url 'app2:manage_user' action item.id %}"
				type="submit">{{ action }}</button>
			</form></td>	
			</tr>
		{% endfor %}
		</ul>
	{% else %}
		<p>No users are available.</p>
		</table>
	{% endif %}
	
	<form action="{% url "logout" %}" method="post">
    		{% csrf_token %}
    		<input type="submit" value="Logout" style="position: fixed; right: 30px; bottom: 50px;">
	</form>

	<label for="update">Update Order #No:</label>
		<input type="text" name="upd_sno">
		<input type="submit" value="Update order" formaction="{% url 'app1:mng_order' "upd" "0" %}">

	 <li><a href="{% url 'app1:product' prd.psno %}">{{prd.pname}}</a></td><td>;;{{prd.pmf}}</a></li> 
{% endcomment %}
  </body>
</html>